version: '3.3'

volumes:
  pg_data:
  static:
  media:
  redoc:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: vladrusinov/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media/recipes/images
      - redoc:/backend/foodgram_backend/docs/
  frontend:
    image: vladrusinov/foodgram_frontend
    depends_on:
      - backend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    image: vladrusinov/foodgram_gateway
    ports:
      - "8000:80"
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/app/media/recipes/images
      - ../frontend/build:/usr/share/nginx/html/
      - redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    restart: always
