version: '3.3'

volumes:
  pg_data:
  static_value:
  media_value:
  redoc:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: vladrusinov/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
  frontend:
    image: vladrusinov/foodgram_frontend
    depends_on:
      - backend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "81:81"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
    restart: always